git add ascii_table.png
git add ERM240128.png
git add macros.h
git add psuedo_avrdude
git add t6963.c
git add atmega328p.conf
git add flash_read.sh
git add main.c
git add README.md
git add t6963.h
git add avrdude.conf
git add flash_write.sh
git add main.h
git add run-avrdude
git add unload.sh
git add avrdude-test
git add getinfo
git add Makefile
git add run_test.sh
git add USART.c
git add avrdude-test2
git add gitadd.sh
git add pinDefines.h
git add sfr_helper.h
git add USART.h
git add binaryMacro.h
git add LCD_chart.png
git add portpins.h
git add spi.c
git add LCD_pinout.png
git add ProMiniPinout.txt
git add spi.h
git add temp/test_gdisp.c
git add temp/test_pwm.c
git status
