git add README.md
git add .gitignore
git add atmega328p.conf
git add avrdude.conf
git add avrdude-test
git add avrdude-test2
git add compile
git add dobus2
git add flash_lcdw.sh
git add flash_read.sh
git add getinfo
git add gitadd.sh
git add main.c
git add Makefile
git add run-avrdude
git add run_lcd.sh
git add run_testports.sh
git add sfr_helper.h
git add lib/t6963.c
git add lib/t6963.h
git add test_ports.c
git add using_tools.txt
git add lib/USART.c
git add lib/USART.h
git add lib/portpins.h
git add lib/pinDefines.h
git add lib/macros.h
git add lib/binaryMacro.h
git add ProMiniPinout.txt
clear
git status
